### ISSUE TITLE
ブロックリストに関する問題

### ISSUE THREAD

**Issue by koyamatakayuki** [enpitut/WakeUp#11]
UGEN起動時はニコ動とyoutubeの二つのサイトをデフォルトでブロックしています。
URL指定してボタンを押すことでブロックサイトは追加できるが、
一度 UGENが終了してしまうと,追加したブロックサイトも消えてしまうという問題があります。

**Comment by anqooqie** [comment]
解決の方針だけ言っておくと、localStorageを使うと解決できます
誰が実装するかは昼会で決める？

**Comment by koyamatakayuki** [comment]
了解
