### ISSUE TITLE
Chrome Web Store には載せないの？

### ISSUE THREAD

**Issue by chiemi627** [enpitut/WakeUp#66]
そちらにある方が使いやすいなぁ〜。
enPiT的にも、ニーズ検証とかユーザテストの段階にはいるときには
いいんじゃないかなーと思います。
登録してないのは何か理由があるのでしょうか？
$5 いるから、とか？

**Comment by strangestorage** [comment]
返信が遅くなり申し訳ありません。
Web Storeへの掲載は、ビジネスモデルの案がきちんと固まってからのほうが良いのではという判断から見送っています。
最終的には掲載する予定です（Twitterアプリケーションの凍結の対応もありますので、いつになるかまだ見通しは立っていません）。

**Comment by chiemi627** [comment]
なるほど了解です。
確かに今はTwitterアプリ凍結の対応が最優先ですね。

ところで「ビジネスモデルの案が固まっていない」とはどういう状況ですか？
単純に状況がわからないので教えてもらえると助かります。

**Comment by strangestorage** [comment]
ビジネスモデルについては、
・WebStoreで有料で売る
・UGENに広告を貼る
を考えていて、後者が濃厚という感じでまとまりつつあったのですが、まだ確定はしていない、というところです。

**Comment by chiemi627** [comment]
なるほどー。そこまで考えているのね。

ビジネスモデルに関してはUGENを今後も運用することを考えているか、
それともあくまでenPiT期間限定のものかによりますね。enPiTの学習項目
としてはビジネスモデル（特に収益）まではカバーしておりませんので
そこは各自の判断でお願いします。（今後の運営体制ということだったら
先日連絡のあったTFFに相談するという手もあります）

よく考えてみたら、ユーザテストをするためだけだったら個別に友人に
頼んで使ってもらうとかという手もあるのでそこまで無理をしてWebStoreに
上げる必要もない…かな？

**Comment by anqooqie** [comment]
[作業強制タイマーUGEN - Chrome ウェブストア](https://chrome.google.com/webstore/detail/%E4%BD%9C%E6%A5%AD%E5%BC%B7%E5%88%B6%E3%82%BF%E3%82%A4%E3%83%9E%E3%83%BCugen/ahigmoamghgjcojanhgiidpglkncciji)で公開したのでclose
