### ISSUE TITLE
残り時間カウントが爆速で減っていく

### ISSUE THREAD

**Issue by anqooqie** [enpitut/WakeUp#8]
## 再現手段

1. 監視スタートボタンを押す
1. タスク完了ボタンを押す
1. 監視スタートボタンを押す
1. タスク完了ボタンを押す
1. （…気が済むまで繰り返す）
1. 監視スタートボタンを押す

**Comment by dulltz** [comment]
この問題と直接関係は無いと思うんだけど、
setInterval()じゃなくてsetTimeout()を再帰的に呼び出す仕組みにしているのはなぜ？

**Comment by anqooqie** [comment]
参考: http://blog.morizotter.com/2014/04/08/javascript-setinterval-settimeout/

```javascript
setInterval(heavyFunction, 1);
```
みたいなことをするとheavyFunction実行が完了しないうちに次のheavyFunctionが実行されてしまって面倒なことになると言われています（実際試したわけではない）
なので、自分は基本的にsetTimeout再帰の書き方を使っており、今回も特に深く考えずsetTimeoutを使っています
今回もsetTimeout再帰の方が最適かどうかは議論の余地があると思います

**Comment by dulltz** [comment]
なるほど！！！
