### ISSUE TITLE
README.md編集の提案

### ISSUE THREAD

**Issue by ug23** [enpitut/WakeUp#9]
アドバイスです。

いまREADME.mdにはplaceholder（ぐへへへへ）が入っていますが
折角なのでプロジェクトの表紙ページ的な感じで整えとくと良いと思います。
マークダウンの書き方はこのページが参考になるかもしれません。
http://codechord.com/2012/01/readme-markdown/
この辺や自分たちでググってみても良いと思います。

- チーム名
- プロダクト名
- メンバー（所属も書いとくと良いかも）
- 概要（「○○をhogehogeする××です」のような）
- エレベーターピッチ

あたりを書いておくとよいと思います。
他のチームのリポジトリでpublicになっているところを覗いて参考にしてみてください。

また、これは発展的内容ですが、リポジトリを見て試してみたいと思った人がすぐ試せるように
* cloneした後どうすれば試せる（使えるようになる）のか * を書いておくと良いと思います。

@strangestorage 
 *リーダブルコード勉強会 in 筑波大* でちょっとやったと思うので実践してみてください。
README.mdを見ただけで試せるようになるガイドがあれば完璧です。

**Comment by strangestorage** [comment]
ご指摘ありがとうございます。
README内容を変更しておきたいと思います。
