### ISSUE TITLE
監視中にChromeを再起動すると残り監視時間表示のバッジが消えずに残る

### ISSUE THREAD

**Issue by anqooqie** [enpitut/WakeUp#95]
現在の仕様では、監視中にChromeを再起動すると監視が停止して監視前の状態に戻るのだが、このとき残り監視時間表示のバッジは消えてしかるべきところ、バッジがゾンビのように生き残り、Chrome終了前と同じ数字を表示し続ける。
つまり、以下のようなちぐはぐな表示になる。（画像は[ユーザのバグ報告](https://twitter.com/akizaki1223/status/695259616326725633)から引用）

![cayo75lviaa1k2w](https://cloud.githubusercontent.com/assets/333517/14480771/09d1de3c-0167-11e6-9315-2ac76e44b126.png)

**Comment by dulltz** [comment]
[chrome.windows.onRemoved](https://developer.chrome.com/extensions/windows#event-onRemoved)
使ったらいけそうだから、自分がバグ修正対応してもいい？

**Comment by anqooqie** [comment]
お願いします

**Comment by dulltz** [comment]
chromeのプロセスが再起動したときのアプリの振る舞いをテストに書きたいんだけど書き方分かる人いますか？

**Comment by anqooqie** [comment]
Chromeが再起動したときの挙動をテストコードで再現できるかどうかってかなり怪しいし、書くのが難しい割にリターンが大してないテストコードは無理して書かなくてもいいんじゃないかなと思う

**Comment by dulltz** [comment]
たしかに
